#!/bin/bash
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source ${DIR}/jamolib

CFILE=../config/backup.conf.sample
declare -A OPTS
declare -A CUST

declare -A CONF
readconfig $CFILE "options"
cp_hash 'CONF' 'OPTS'
unset CONF

declare -A CONF
readconfig $CFILE "customers"
cp_hash 'CONF' 'CUST'
unset CONF

echo "Options Region"
for i in "${!OPTS[@]}"
do
  KEY=$i
  VAL=${OPTS[$i]}
  echo "Key: $KEY, val: $VAL"
done

echo "Customers Region"
for i in "${!CUST[@]}"
do
  KEY=$i
  VAL=${CUST[$i]}
  echo "Key: $KEY, val: $VAL"
done
